#!/bin/sh
#
# boomi         Start or stop Dell Boomi ETL engine
#
# chkconfig: 2345 08 92
# description:  Starts, stops and restarts Dell Boomi
#
### BEGIN INIT INFO
# Provides: boomi
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop Dell Boomi
# Description: Start, stop and save Dell Boomi
### END INIT INFO

# Source function library.
. /etc/init.d/functions

start() {
    /etc/init.d/BoomiLink start
    #return $ret
}

stop() {
    /etc/init.d/BoomiLink stop
    #return $ret
}

status() {
    /etc/init.d/BoomiLink status
    return 0
}

case "$1" in
    start)
        start
        RETVAL=$?
        ;;
    stop)
        stop
        RETVAL=$?
        ;;
    restart|force-reload)
        stop
        start
        ;;
    status)
        status
        RETVAL=$?
        ;;
    *)
        echo $"Usage: {start|stop|status}"
        RETVAL=2
        ;;
esac

exit $RETVAL
